<a href="https://colab.research.google.com/github/JaeKyunKo/Engineering_Department_Tutoring/blob/main/Tutoring_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy (Python Library)**

List (Python Data Structure)

In [1]:
#List Declaration
lstOne, lstTwo = list(), list()

In [2]:
for i in range(5) :
  lstOne.append(i)
  lstTwo.append(i+1)

In [4]:
print(lstOne, lstTwo)

[0, 1, 2, 3, 4] [1, 2, 3, 4, 5]


In [6]:
lstNew = lstOne + lstTwo

In [7]:
len(lstNew)

10

**Import Numpy Libraray**

In [8]:
import numpy as np

**Data Types in Numpy**

In [80]:
np.int

int

In [81]:
np.float

float

In [82]:
np.complex

complex

In [83]:
np.bool

bool

In [84]:
np.string_

numpy.bytes_

**Numpy Array Declaration**

np.array(list_name, data_type)

data_type -> int / float / str / ...

In [20]:
arrayExample = np.array([1,2])

In [40]:
arrayOne = np.array(lstOne, float)
arrayTwo = np.array(lstTwo, int)

In [41]:
for i in range(5) :
  print(type(arrayOne[i]))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [42]:
print(arrayOne, arrayTwo)
print(type(lstOne), type(lstTwo))
print(type(arrayOne), type(arrayTwo))

[0. 1. 2. 3. 4.] [1 2 3 4 5]
<class 'list'> <class 'list'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


Index Addition Implementation

In [43]:
arrayNew = arrayOne + arrayTwo

In [44]:
print(arrayNew)

[1. 3. 5. 7. 9.]


Same Implementation with Python list

In [18]:
for i in range(5) :
  arrayNew[i] = arrayOne[i] + arrayTwo[i]

In [19]:
print(arrayNew)

[1 3 5 7 9]


**2D or N-Dimensional Array Declaration**

In [23]:
array2D = np.array([[1,2,3], [4,5,6]])

In [24]:
print(array2D)

[[1 2 3]
 [4 5 6]]


**Finding Array Size(Shape)**

In [45]:
n, m = np.shape(array2D)

In [48]:
print(n, m)

2 3


**Initializing Array Size**

Python -> Declaration + Initialization 

Therefore, cannot set the size of array before Initialization

In [50]:
n, m = 3, 3
arrayInit = np.zeros((n,m))

In [51]:
print(arrayInit)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [53]:
arrayInit = np.ones((n,m))
print(arrayInit)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [54]:
numFull = 255
arrayInit = np.full((n,m), numFull)
print(arrayInit)

[[255 255 255]
 [255 255 255]
 [255 255 255]]


In [55]:
unitMatrix = np.eye(3)
print(unitMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [72]:
startPoint = 0
endPoint = 10
stepSize = 1
np.arange(startPoint ,endPoint ,stepSize)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
divisionSize = 10
np.linspace(startPoint, endPoint, divisionSize)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [75]:
np.random.random((2,2))

array([[0.90007617, 0.36435282],
       [0.48766634, 0.93217602]])

In [76]:
arrayEmpty = np.empty((3,3))

In [79]:
print(arrayEmpty)

[[ 1.11111111  2.22222222  3.33333333]
 [ 4.44444444  5.55555556  6.66666667]
 [ 7.77777778  8.88888889 10.        ]]


**Numpy Array Indexing and Slicing**

In [89]:
#Declaring and Initializing New 2D List
lstNew = list()
for i in range(10) :
  lstAppend = list()
  for j in range(10) :
    lstAppend.append(i * j)
  lstNew.append(lstAppend)

In [90]:
#List To Array
arrayNew = np.array(lstNew)

In [96]:
arraySliced = arrayNew[:7]

In [101]:
arraySlicedSliced = arraySliced[:, :5]

In [104]:
print("Original Array")
print(arrayNew)
print("Sliced Array")
print(arraySliced)
print("Twice Sliced Array")
print(arraySlicedSliced)

Original Array
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]
Sliced Array
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]]
Twice Sliced Array
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]
 [ 0  5 10 15 20]
 [ 0  6 12 18 24]]


**Numpy Array Reshape**

In [152]:
np.shape(arrayNew)

(10, 10)

In [163]:
arrayNew.reshape(100, -1) #100x1 Array
arrayNew.reshape(-1, 100) #1x100 Array

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9,  0,  2,  4,  6,  8, 10, 12, 14, 16, 18,  0,  3,
         6,  9, 12, 15, 18, 21, 24, 27,  0,  4,  8, 12, 16, 20, 24, 28,
        32, 36,  0,  5, 10, 15, 20, 25, 30, 35, 40, 45,  0,  6, 12, 18,
        24, 30, 36, 42, 48, 54,  0,  7, 14, 21, 28, 35, 42, 49, 56, 63,
         0,  8, 16, 24, 32, 40, 48, 56, 64, 72,  0,  9, 18, 27, 36, 45,
        54, 63, 72, 81]])

**Numpy Array Mathematics**

In [111]:
arrayOne = np.random.randint(10, size = (3,3))
arrayTwo = np.random.randint(10, size = (3,3))

In [116]:
print(arrayOne)
print()
print(arrayTwo)

[[6 3 4]
 [3 3 2]
 [0 3 3]]

[[6 5 8]
 [8 4 7]
 [5 6 2]]


In [127]:
print(arrayOne + arrayTwo)

[[12  8 12]
 [11  7  9]
 [ 5  9  5]]


In [128]:
np.add(arrayOne, arrayTwo)

array([[12,  8, 12],
       [11,  7,  9],
       [ 5,  9,  5]])

In [129]:
print(arrayOne - arrayTwo)

[[ 0 -2 -4]
 [-5 -1 -5]
 [-5 -3  1]]


In [130]:
np.subtract(arrayOne, arrayTwo)

array([[ 0, -2, -4],
       [-5, -1, -5],
       [-5, -3,  1]])

In [134]:
np.divide(arrayOne, arrayTwo)

array([[1.        , 0.6       , 0.5       ],
       [0.375     , 0.75      , 0.28571429],
       [0.        , 0.5       , 1.5       ]])

In [135]:
np.exp(arrayOne)

array([[403.42879349,  20.08553692,  54.59815003],
       [ 20.08553692,  20.08553692,   7.3890561 ],
       [  1.        ,  20.08553692,  20.08553692]])

In [136]:
np.sqrt(arrayOne)

array([[2.44948974, 1.73205081, 2.        ],
       [1.73205081, 1.73205081, 1.41421356],
       [0.        , 1.73205081, 1.73205081]])

In [138]:
np.sin(arrayOne)

array([[-0.2794155 ,  0.14112001, -0.7568025 ],
       [ 0.14112001,  0.14112001,  0.90929743],
       [ 0.        ,  0.14112001,  0.14112001]])

In [139]:
np.cos(arrayOne)

array([[ 0.96017029, -0.9899925 , -0.65364362],
       [-0.9899925 , -0.9899925 , -0.41614684],
       [ 1.        , -0.9899925 , -0.9899925 ]])

In [140]:
np.dot(arrayOne, arrayTwo) #2D Array -> np.dot == np.matmul

array([[80, 66, 77],
       [52, 39, 49],
       [39, 30, 27]])

In [141]:
np.matmul(arrayOne, arrayTwo)

array([[80, 66, 77],
       [52, 39, 49],
       [39, 30, 27]])

In [142]:
np.transpose(arrayOne) #Very Useful when Finding Eigenvector / Eigenvalue

array([[6, 3, 0],
       [3, 3, 3],
       [4, 2, 3]])

In [144]:
np.linalg.inv(arrayOne)

array([[ 0.11111111,  0.11111111, -0.22222222],
       [-0.33333333,  0.66666667,  0.        ],
       [ 0.33333333, -0.66666667,  0.33333333]])

**Element Comparison**

In [149]:
print(arrayOne)
print(arrayTwo)

[[6 3 4]
 [3 3 2]
 [0 3 3]]
[[6 5 8]
 [8 4 7]
 [5 6 2]]


In [148]:
arrayOne == arrayTwo

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [150]:
arrayOne > arrayTwo

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

**Assignment Review**

**2-1. 어떻게 numpy의 array를 나눌 수 있을까?**

**Splitting Arrays!**
**[[1 2 3], [4 5 6]]으로 만들어 져있는 numpy array을 [1 2 3] array과 [4 5 6] array로 나누는 것을 실습해보자.**

**그리고 [1 4] [2 5] [3 6]으로도 나누어보자.**

In [166]:
array2D = np.array([[1,2,3], [4,5,6]])

In [170]:
arrayIdxOne = array2D[0]
arrayIdxTwo = array2D[1]

In [171]:
print(arrayIdxOne)
print(arrayIdxTwo)

[1 2 3]
[4 5 6]


In [174]:
for i in range(3) : #0, 1, 2
  print(array2D[:, i:i+1])

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


**2-2. 연립방정식을 풀어보자.**

**3x1+2x2+x3=7** 

**x1−x2+3x3=3** 

**5x1+4x2−2x3=1**

**위의 선형 연립방정식의 해  x1,x2,x3 를 구해보자.**

In [176]:
arrayA = np.array([[3,2,1], [1,-1,3], [5,4,-2]]) #3x3 Matrix
arrayB = np.array([[7], [3], [1]]) #3x1 Matrix

In [177]:
invMat = np.linalg.inv(arrayA)

In [178]:
xMatrix = np.matmul(invMat, arrayB)

In [179]:
print(xMatrix) #Answer Matrix

[[-3.]
 [ 6.]
 [ 4.]]


In [180]:
#Revision -> AX = B
print(np.matmul(arrayA, xMatrix))

[[7.]
 [3.]
 [1.]]
